config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  # get 'home/index'
  root "home#index"
  get 'home/about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :contacts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]
  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone_number, :twitter,:user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name,class:"form-control",placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name,class:"form-control",placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email,class:"form-control",placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone_number,class:"form-control",placeholder:"Phone Number" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :twitter,class:"form-control",placeholder:"Twitter" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id,id: :friend_user_id,value:current_user.id,type: :hidden,class:"form-control",placeholder:"Twitter" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1 class="mt-4 mb-4">Contacts</h1>

<table class="table table-bordered table-striped table-hover mx-auto">
  <thead class="thead-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Twitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone_number %></td>
        <td><%= contact.twitter %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Contact', new_contact_path, class:"btn btn-secondary" %>

app/views/contacts/new.html.erb
<h1 class="mt-4 mb-4">New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path,class:"btn btn-dark mt-2" %>

app/views/contacts/show.html.erb
<div class="jumbotron">
<h1>
  <strong>
   <%= @contact.first_name %>  <%= @contact.last_name %>
  </strong>
 
</h1>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @contact.phone_number %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @contact.twitter %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact),class:"btn btn-secondary" %> 
<%= link_to 'Back', contacts_path, class:"btn btn-dark" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <!-- Brand -->
  <%= link_to "EzTech",root_path,class:"navbar-brand"%>
  

  <!-- Toggler/collapsibe Button -->
  <%# <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button> %>

  <!-- Navbar links -->
  <%# <div class="collapse navbar-collapse" id="collapsibleNavbar"> %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
    <%= link_to "About Us",home_about_path,class:"nav-link"%>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
    <%= link_to "Contacts",contacts_path,class:"nav-link"%>
        </li>
      <li class="nav-item">
    <%= link_to "Add Contact",new_contact_path,class:"nav-link"%>
        </li>
         <li class="nav-item">
    <%= link_to "Edit profile",edit_user_registration_path,class:"nav-link"%>  
        </li>
         <li class="nav-item">
    <%= link_to "Sign out",destroy_user_session_path,method: :delete,class:"nav-link"%>
        
        </li>
       

        <% else %>
        <li class="nav-item">
    <%= link_to "Sign up",new_user_registration_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
    <%= link_to "Sign in",new_user_session_path,class:"nav-link"%>
        </li>
      <% end %>
    </ul>
    
  <%# </div> %>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<div class="container">



        <h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<h1>EzTech</h1>
<h2>jhejhenrf</h2>
    <button class="btn btn-lg btn-success" value="Submit">Primary</button>
    <br/>
    <br/>
    <input type="button" class="btn btn-lg btn-primary" value="submit">

</div>
Example
<div class="dropdown">
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
    Dropdown button
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="#">Link 1</a>
    <a class="dropdown-item" href="#">Link 2</a>
    <a class="dropdown-item" href="#">Link 3</a>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show mt-2" role="alert">
 <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>First</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render("home/header") %>
  <div class="container">
  <% if notice %>
  <%= render("layouts/alerts") %>
  <% end %>
    <%= yield %>
  </div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>